version: "2"
services:
  #自定义镜像
  #运行jar包
  RunJar:
    image: runjar:1.0
    build:
      context: .
      dockerfile: springboot
    container_name: RunJar
    privileged: true
    ports:
      - 8080:8080
    networks:
      - dev
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge