version: "2"
services:
  Portainer:
    image: docker.io/portainer/portainer
    container_name: Portainer
    restart: always
    privileged: true
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  VISMARKETING:
    image: runjar_prod:2.0
    container_name: VISMARKETING
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /root/runjar.sh:/runjar.sh
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com

# docker run --restart=always --name Portainer -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock docker.io/portainer/portainer
# docker run --name VISMARKETING -d -p 8080:8080 -v /root/runjar.sh:/runjar.sh runjar_prod:2.0