#docker-compose版本
version: "2"
#服务
services:
  #使用阿里云MySQL镜像创建容器
  MySQL:
    #镜像文件
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/mysql:5.7
    #容器名称
    container_name: MySQL
    #root权限
    privileged: true
    #环境变量
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    #端口映射
    ports:
      - 3306:3306
    #挂载卷
    volumes:
      - /opt/docker/mysql/config/my.cnf:/etc/my.cnf
      - /opt/docker/mysql/data:/var/lib/mysql
    #网络
    networks:
      dev:
        ipv4_address: 172.20.0.4
    #说明
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
#网络
networks:
  dev:
    #桥接网络
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1