version: "2"
services:
  MySQL:
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/mysql:5.7
    container_name: MySQL
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - /opt/docker/mysql/config/my.cnf:/etc/my.cnf
      - /opt/docker/mysql/data:/var/lib/mysql
    networks:
      dev:
        ipv4_address: 172.20.2.2
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Redis:
    image: docker.io/redis
    container_name: Redis
    restart: always
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - /opt/docker/redis/config/redis.conf:/etc/redis/redis.conf
      - /opt/docker/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      dev:
        ipv4_address: 172.20.2.3
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  MongoDB:
    image: docker.io/mongo
    container_name: MongoDB
    restart: always
    privileged: true
    ports:
      - 27017:27017
    volumes:
      - /opt/docker/mongodb/data:/data/db
    networks:
      dev:
        ipv4_address: 172.20.2.4
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  PostgreSQL:
    image: docker.io/postgres:10
    container_name: PostgreSQL
    restart: always
    privileged: true
    ports:
      - 5432:5432
    volumes:
      - /opt/docker/postgresql/data:/var/lib/postgresql/data
    networks:
      dev:
        ipv4_address: 172.20.2.5
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/16
          gateway: 172.20.2.1