version: "2"
services:
  Nginx:
    image: docker.io/nginx
    container_name: Nginx
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - /opt/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/docker/nginx/apps/:/opt/apps/
    networks:
      dev:
        ipv4_address: 172.20.3.2
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/16
          gateway: 172.20.3.1