version: "2"
services:
  Token:
    image: runjar_prod:1.0
    container_name: Token
    privileged: true
    ports:
      - 8082:8080
    networks:
      dev:
        ipv4_address: 172.20.4.2
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  #MQ:
    #image: runjar_prod:1.0
    #container_name: MQ
    #privileged: true
    #ports:
      #- 8083:8080
    #networks:
      #dev:
        #ipv4_address: 172.20.4.3
    #labels:
      #- name=ybxxszl
      #- email=1062837400@qq.com
  Eureka:
    image: runjar_prod:1.0
    container_name: Eureka
    privileged: true
    ports:
      - 8083:8080
    networks:
      dev:
        ipv4_address: 172.20.4.3
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Admin:
    image: runjar_prod:1.0
    container_name: Admin
    privileged: true
    ports:
      - 8084:8080
    networks:
      dev:
        ipv4_address: 172.20.4.4
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.4.0/16
          gateway: 172.20.4.1
