version: "2"
services:
  QS1:
    image: runjar_prod:1.0
    container_name: QS1
    privileged: true
    ports:
      - 8282:8080
    networks:
      dev:
        ipv4_address: 172.20.5.2
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS2:
    image: runjar_prod:1.0
    container_name: QS2
    privileged: true
    ports:
      - 8383:8080
    networks:
      dev:
        ipv4_address: 172.20.5.3
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS3:
    image: runjar_prod:1.0
    container_name: QS3
    privileged: true
    ports:
      - 8484:8080
    networks:
      dev:
        ipv4_address: 172.20.5.4
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS4:
    image: runjar_prod:1.0
    container_name: QS4
    privileged: true
    ports:
      - 8585:8080
    networks:
      dev:
        ipv4_address: 172.20.5.5
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS5:
    image: runjar_prod:1.0
    container_name: QS5
    privileged: true
    ports:
      - 8686:8080
    networks:
      dev:
        ipv4_address: 172.20.5.6
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS6:
    image: runjar_prod:1.0
    container_name: QS6
    privileged: true
    ports:
      - 8787:8080
    networks:
      dev:
        ipv4_address: 172.20.5.7
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS7:
    image: runjar_prod:1.0
    container_name: QS7
    privileged: true
    ports:
      - 887:8080
    volumes:
      - /opt/docker/qs/qs7/logs:/logs
    networks:
      dev:
        ipv4_address: 172.20.5.8
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS8:
    image: runjar_prod:1.0
    container_name: QS8
    privileged: true
    ports:
      - 888:8080
    volumes:
      - /opt/docker/qs/qs8/logs:/logs
    networks:
      dev:
        ipv4_address: 172.20.5.9
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  VISMARKETING1:
    image: runjar:1.0
    container_name: VISMARKETING1
    privileged: true
    ports:
      - 8891:8080
    networks:
      dev:
        ipv4_address: 172.20.5.11
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  VISMARKETING2:
    image: runjar:1.0
    container_name: VISMARKETING2
    privileged: true
    ports:
      - 8892:8080
    networks:
      dev:
        ipv4_address: 172.20.5.12
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.5.0/16
          gateway: 172.20.5.1
