version: "2"
services:
  Grafana:
    image: docker.io/grafana/grafana
    container_name: Grafana
    restart: always
    privileged: true
    ports:
      - 3000:3000
    networks:
      dev:
        ipv4_address: 172.20.6.2
    volumes:
      - /opt/docker/grafana/:/etc/grafana
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Prometheus:
    image: docker.io/prom/prometheus
    container_name: Prometheus
    restart: always
    privileged: true
    ports:
      - 9090:9090
    networks:
      dev:
        ipv4_address: 172.20.6.3
    volumes:
      - /opt/docker/prometheus/:/etc/prometheus
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.6.0/16
          gateway: 172.20.6.1