version: "2"
services:
  Portainer:
    image: docker.io/portainer/portainer
    container_name: Portainer
    restart: always
    privileged: true
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  NextCloud:
    image: docker.io/nextcloud
    container_name: NextCloud
    restart: always
    privileged: true
    ports:
      - 90:80
    volumes:
      - /docker/nextcloud:/data
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  H5ai:
    image: docker.io/ilemonrain/h5ai:full
    container_name: H5ai
    restart: always
    privileged: true
    ports:
      - 85:80
    volumes:
      - /docker/h5ai:/h5ai
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  # cn=admin,dc=ybxxszl,dc=com
  # cn=qs,dc=ybxxszl,dc=com
  PHPLDAPAdmin:
    image: docker.io/osixia/phpldapadmin
    container_name: PHPLDAPAdmin
    restart: always
    privileged: true
    ports:
      - 81:80
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=OpenLDAP
      - PHPLDAPADMIN_HTTPS=false
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  OpenLDAP:
    image: docker.io/osixia/openldap
    container_name: OpenLDAP
    restart: always
    privileged: true
    ports:
      - 389:389
      - 636:636
    volumes:
      - /docker/openldap/slapd.d:/etc/ldap/slapd.d
      - /docker/openldap/ldap:/var/lib/ldap
    environment:
      - LDAP_ORGANISATION=ybxxszl
      - LDAP_DOMAIN=ybxxszl.com
      - LDAP_ADMIN_PASSWORD=wjy13944997040
      - LDAP_TLS=false
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Gerrit:
    image: docker.io/openfrontier/gerrit:2.16.10
    container_name: Gerrit
    restart: always
    privileged: true
    ports:
      - 8081:8080
      - 29419:29418
    volumes:
      - /docker/gerrit:/var/gerrit/review_site
    environment:
      WEBURL: http://49.233.155.139:8081/
      SSHD_ADVERTISE_ADDR: 49.233.155.139:29419
      DATABASE_TYPE: postgresql
      DATABASE_HOSTNAME: PostgreSQL-Gerrit
      DATABASE_DATABASE: gerrit
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: 1234
      AUTH_TYPE: LDAP
      LDAP_SERVER: OpenLDAP
      LDAP_USERNAME: cn=admin,dc=ybxxszl,dc=com
      LDAP_PASSWORD: wjy13944997040
      LDAP_ACCOUNTBASE: cn=qs,dc=ybxxszl,dc=com
      LDAP_ACCOUNTPATTERN: (&(objectClass=person)(uid=$${username}))
      LDAP_ACCOUNTFULLNAME: cn
      LDAP_ACCOUNTEMAILADDRESS: mail
      SMTP_SERVER: smtp.qq.com
      SMTP_SERVER_PORT: 465
      SMTP_ENCRYPTION: tls
      SMTP_USER: 1062837400@qq.com
      SMTP_PASS: zdayfjmjsnfjbbhh
      USER_EMAIL: 1062837400@qq.com
      GITWEB_TYPE: gitiles
      GERRIT_INIT_ARGS: --install-all-plugins
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  # cd $REDMINE_HOME/plugins
  # git clone https://github.com/mikitex70/redmine_drawio.git
  Redmine:
    image: docker.io/redmine
    container_name: Redmine
    restart: always
    privileged: true
    ports:
      - 3001:3000
    volumes:
      - /docker/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - /docker/redmine/files:/usr/src/redmine/files
      - /docker/redmine/plugins:/usr/src/redmine/plugins
      - /docker/redmine/repos:/var/lib/redmine/repos
    environment:
      REDMINE_DB_POSTGRES: PostgreSQL-Redmine
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: admin
      REDMINE_DB_PASSWORD: 1234
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  PostgreSQL-Gerrit:
    image: docker.io/postgres:10
    container_name: PostgreSQL-Gerrit
    restart: always
    privileged: true
    ports:
      - 54321:5432
    volumes:
      - /docker/postgresql/gerrit:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gerrit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  PostgreSQL-Redmine:
    image: docker.io/postgres:10
    container_name: PostgreSQL-Redmine
    restart: always
    privileged: true
    ports:
      - 54322:5432
    volumes:
      - /docker/postgresql/redmine:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  # chown -R 1000 /docker/jenkins/jenkins_home
  Jenkins:
    image: docker.io/jenkins/jenkins:lts
    container_name: Jenkins
    restart: always
    privileged: true
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - /docker/jenkins/jenkins_home:/var/jenkins_home
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Gitblit:
    image: docker.io/jacekkow/gitblit
    container_name: Gitblit
    restart: always
    privileged: true
    ports:
      - 8880:8080
      - 8443:8443
      - 9418:9418
      - 29418:29418
    volumes:
      - /docker/gitblit/gitblit-data:/opt/gitblit-data
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  # chown -R 200 /docker/nexus/data
  Nexus:
    image: docker.io/sonatype/nexus3
    container_name: Nexus
    restart: always
    privileged: true
    ports:
      - 8881:8081
    volumes:
      - /docker/nexus/data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  MySQL:
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/mysql:5.7
    container_name: MySQL
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - /docker/mysql/config/my.cnf:/etc/my.cnf
      - /docker/mysql/data:/var/lib/mysql
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Redis:
    image: docker.io/redis
    container_name: Redis
    restart: always
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - /docker/redis/config/redis.conf:/etc/redis/redis.conf
      - /docker/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Redis-Master:
    image: docker.io/redis
    container_name: Redis-Master
    restart: always
    privileged: true
    ports:
      - 6400:6379
    volumes:
      - /docker/redisms/conf/redis-master_6400.conf:/etc/redis/redis-master_6400.conf
      - /docker/redisms/data/master:/data
    command: redis-server /etc/redis/redis-master_6400.conf
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Redis-Slave:
    image: docker.io/redis
    container_name: Redis-Slave
    restart: always
    privileged: true
    ports:
      - 6401:6379
    volumes:
      - /docker/redisms/conf/redis-slave_6401.conf:/etc/redis/redis-slave_6401.conf
      - /docker/redisms/data/slave:/data
    command: redis-server /etc/redis/redis-slave_6401.conf
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: Elasticsearch
    hostname: Elasticsearch
    restart: always
    privileged: true
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /docker/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    environment:
      - discovery.type=single-node
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: Kibana
    hostname: Kibana
    restart: always
    privileged: true
    ports:
      - 5601:5601
    links:
      - Elasticsearch:elasticsearch
    depends_on:
      - Elasticsearch
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Nacos:
    image: docker.io/nacos/nacos-server
    container_name: Nacos
    restart: always
    privileged: true
    environment:
      - MODE=standalone
    ports:
      - 8848:8848
    volumes:
      - /docker/nacos/custom.properties:/home/nacos/init.d/custom.properties
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Admin:
    image: runjar_prod:1.0
    container_name: Admin
    restart: always
    privileged: true
    ports:
      - 8080:8080
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  Token:
    image: runjar_prod:1.0
    container_name: Token
    restart: always
    privileged: true
    ports:
      - 8181:8080
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  QS:
    image: runjar_prod:1.0
    container_name: QS
    restart: always
    privileged: true
    ports:
      - 8282:8080
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  VISMARKETING:
    image: runjar_prod:2.0
    container_name: VISMARKETING
    privileged: true
    ports:
      - 8888:8080
      - 9090:9090
    volumes:
      - /root/runjar.sh:/runjar.sh
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com