version: "2"
services:
  #Docker可视化工具Portainer
  Portainer:
    image: docker.io/portainer/portainer
    container_name: Portainer
    privileged: true
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dev:
        ipv4_address: 172.20.0.2
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  #使用官方Redis镜像创建容器
  Redis:
    #镜像文件
    image: docker.io/redis
    #容器名称
    container_name: Redis
    #root权限
    privileged: true
    #端口映射
    ports:
      - 6379:6379
    #挂载卷
    volumes:
      - /opt/docker/redis/config/redis.conf:/etc/redis/redis.conf
      - /opt/docker/redis/data:/data
    #执行命令
    command: redis-server /etc/redis/redis.conf
    #网络
    networks:
      dev:
        ipv4_address: 172.20.0.3
    #说明
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  #使用阿里云MySQL镜像创建容器
  MySQL:
    #镜像文件
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/mysql:5.7
    #容器名称
    container_name: MySQL
    #root权限
    privileged: true
    #环境变量
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    #端口映射
    ports:
      - 3306:3306
    #挂载卷
    volumes:
      - /opt/docker/mysql/config/my.cnf:/etc/my.cnf
      - /opt/docker/mysql/data:/var/lib/mysql
    #网络
    networks:
      dev:
        ipv4_address: 172.20.0.4
    #说明
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
  #Nginx
  Nginx:
    image: docker.io/nginx
    container_name: Nginx
    privileged: true
    ports:
      - 80:80
    volumes:
      - /opt/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/docker/nginx/apps/:/opt/apps/
    networks:
      dev:
        ipv4_address: 172.20.0.5
    labels:
      - name=ybxxszl
      - email=1062837400@qq.com
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1