#数据库密码解析publicKey
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJfyO3dlTHcDEu9XNTSjsVHV9T3ZhPC6IpnmPAuvEo8wdXZVr18+LICQy3SJxqCUdUIv/UyGDZlNs3Jg8Z83TBMCAwEAAQ==
spring:
  datasource:
    #配置数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
      url: jdbc:mysql://192.168.1.17:3306/qs?useSSL=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
      username: root
      password: QBynaBhwk6aFl+Mzrs1qvZOPA1QXigArI9Oscgave3paEPetDMBfqZ55cbpG+ayHeE20l4eoIw6ZTdGuWSZFPQ==
      driver-class-name: com.mysql.jdbc.Driver
      #配置数据库密码解密
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey}
      #初始化连接池时创建的连接数
      initial-size: 10
      #连接池中最小连接数
      min-idle: 10
      #连接池中最大连接数
      max-active: 30
      #连接最大等待时间
      max-wait: 10
      #保活
      keep-alive: true
      filter:
        #数据库密码加密
        config:
          #启用数据库密码加密
          enabled: true
        #打印日志
        log4j2:
          #打印日志SQL
          enabled: true
          #打印可执行SQL
          statement-executable-sql-log-enable: true
  redis:
    database: 0
    host: 192.168.1.17
    port: 6379
    password: 1234
    timeout: 10000
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        max-wait: 100000
        testOnBorrow: true
        testOnReturn: true
  mvc:
    #关闭SpringBoot显示图标
    favicon:
      enabled: false
  #电子邮件
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 1062837400@qq.com
    #授权码
    password: zdayfjmjsnfjbbhh
    test-connection: true
  #应用
  application:
    #名称
    name: QS
  #Spring Admin
  boot:
    admin:
      #客户端
      client:
        #实例
        instance:
          #IP
          prefer-ip: true
        #注册多个服务
        register-once: false
        #注册地址
        url:
          - http://127.0.0.1:8080/qs

#管理
management:
  #公开所有端点
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  #展示健康详细信息
  endpoint:
    health:
      show-details: ALWAYS
  #关闭健康检查
  health:
    defaults:
      enabled: false

info:
  app:
    name: 调查问卷
    msg: 生命可以归结为一种简单的选择，要么忙于生存，要么赶着去死。谦虚、谨慎、戒骄、戒躁。

mybatis-plus:
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
  #配置mapper.xml位置
  mapper-locations: classpath:mapper/*/*.xml

server:
  #访问路径
  servlet:
    context-path: /qs
  tomcat:
    #accesslog
    accesslog:
      #开启accesslog
      enabled: true
      #日志路径
      directory: ./logs/accesslog
      #日志名称前缀
      prefix: accesslog
      #日志名称后缀
      suffix: .log
      #日志每小时封存
      file-date-format: .yyyy-MM-dd-HH

#日志
logging:
  pattern:
    #输出到控制台的日志格式
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%logger{50}] - %msg%n"
    #输出到文件的日志格式
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%logger{50}] - %msg%n"
  level:
    root: info
  file: qs.log

#是否开启swagger
swagger:
  enable: true

#授权服务地址
token:
  service:
    url: http://token/token/

#邮件报警
mailcall:
  #发送人
  from: 1062837400@qq.com
  #接收人
  to: 1062837400@qq.com